const path = require("node:path");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    path.join(__dirname, "index.html"),
    path.join(__dirname, "src/**/*.{ts,tsx,js,jsx}"),
  ],
  // Safelist for classes that Tailwind's content scanner may miss
  safelist: [
    // Essential layout classes
    "flex",
    "flex-col",
    "flex-row",
    "flex-1",
    "flex-none",
    "flex-shrink-0",
    "flex-grow",
    "h-full",
    "w-full",
    "min-h-0",
    "min-w-0",
    "relative",
    "absolute",
    "fixed",
    "inset-0",
    "overflow-hidden",
    "overflow-auto",
    "overflow-y-auto",
    "overflow-x-auto",
    "items-center",
    "items-start",
    "items-end",
    "items-stretch",
    "justify-center",
    "justify-start",
    "justify-end",
    "justify-between",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "p-0",
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "m-0",
    "m-1",
    "m-2",
    "m-3",
    "m-4",
    "space-x-1",
    "space-x-2",
    "space-y-1",
    "space-y-2",
    // Icon sizes
    "h-3",
    "w-3",
    "h-3.5",
    "w-3.5",
    "h-4",
    "w-4",
    "h-5",
    "w-5",
    // Text alignment
    "text-left",
    "text-center",
    "text-right",
    // Status colors for git diff stats
    "text-green-600",
    "text-red-600",
    // Button component variants (CVA)
    "h-9",
    "h-10",
    "h-11",
    "px-3",
    "px-4",
    "px-8",
    "py-2",
    "rounded-md",
    "bg-primary",
    "text-primary-foreground",
    "hover:bg-primary/90",
    "bg-destructive",
    "text-destructive-foreground",
    "hover:bg-destructive/90",
    "border",
    "border-input",
    "bg-background",
    "hover:bg-accent",
    "hover:text-accent-foreground",
    "bg-secondary",
    "text-secondary-foreground",
    "hover:bg-secondary/80",
    "text-primary",
    "underline-offset-4",
    "hover:underline",
    "w-10",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
